"""국가명 한글 매핑.

FIFA API는 영문 팀명과 3자리 국가코드(IdCountry)를 준다.
코드 우선으로 한글명을 찾고, 없으면 영문명, 그래도 없으면 원본을 반환한다.
"""
from __future__ import annotations

# 2026 월드컵 본선 + 흔한 팀들 (FIFA 3자리 코드 기준)
KO_BY_CODE = {
    "ALG": "알제리",
    "ARG": "아르헨티나",
    "AUS": "호주",
    "AUT": "오스트리아",
    "BEL": "벨기에",
    "BIH": "보스니아",
    "BRA": "브라질",
    "CPV": "카보베르데",
    "CAN": "캐나다",
    "COL": "콜롬비아",
    "COD": "콩고민주공화국",
    "CGO": "콩고",
    "CRO": "크로아티아",
    "CUW": "쿠라소",
    "CZE": "체코",
    "CIV": "코트디부아르",
    "ECU": "에콰도르",
    "EGY": "이집트",
    "ENG": "잉글랜드",
    "FRA": "프랑스",
    "GER": "독일",
    "GHA": "가나",
    "HAI": "아이티",
    "IRN": "이란",
    "IRQ": "이라크",
    "JPN": "일본",
    "JOR": "요르단",
    "KOR": "대한민국",
    "PRK": "북한",
    "MEX": "멕시코",
    "MAR": "모로코",
    "NED": "네덜란드",
    "NZL": "뉴질랜드",
    "NOR": "노르웨이",
    "PAN": "파나마",
    "PAR": "파라과이",
    "POR": "포르투갈",
    "QAT": "카타르",
    "KSA": "사우디아라비아",
    "SCO": "스코틀랜드",
    "SEN": "세네갈",
    "RSA": "남아공",
    "ESP": "스페인",
    "SWE": "스웨덴",
    "SUI": "스위스",
    "TUN": "튀니지",
    "TUR": "튀르키예",
    "USA": "미국",
    "URU": "우루과이",
    "UZB": "우즈베키스탄",
    "COK": "쿡 제도",
    "NGA": "나이지리아",
    "CMR": "카메룬",
    "GAB": "가봉",
    "CHI": "칠레",
    "PER": "페루",
    "BOL": "볼리비아",
    "VEN": "베네수엘라",
    "PAR2": "파라과이",
}

# 영문명 -> 한글 (코드가 없거나 다른 소스용 폴백)
KO_BY_NAME = {
    "Algeria": "알제리",
    "Argentina": "아르헨티나",
    "Australia": "호주",
    "Austria": "오스트리아",
    "Belgium": "벨기에",
    "Bosnia and Herzegovina": "보스니아",
    "Brazil": "브라질",
    "Cabo Verde": "카보베르데",
    "Cape Verde": "카보베르데",
    "Canada": "캐나다",
    "Colombia": "콜롬비아",
    "Congo DR": "콩고민주공화국",
    "DR Congo": "콩고민주공화국",
    "Croatia": "크로아티아",
    "Curaçao": "쿠라소",
    "Curacao": "쿠라소",
    "Czechia": "체코",
    "Czech Republic": "체코",
    "Côte d'Ivoire": "코트디부아르",
    "Cote d'Ivoire": "코트디부아르",
    "Ivory Coast": "코트디부아르",
    "Ecuador": "에콰도르",
    "Egypt": "이집트",
    "England": "잉글랜드",
    "France": "프랑스",
    "Germany": "독일",
    "Ghana": "가나",
    "Haiti": "아이티",
    "IR Iran": "이란",
    "Iran": "이란",
    "Iraq": "이라크",
    "Japan": "일본",
    "Jordan": "요르단",
    "Korea Republic": "대한민국",
    "South Korea": "대한민국",
    "Korea DPR": "북한",
    "North Korea": "북한",
    "Mexico": "멕시코",
    "Morocco": "모로코",
    "Netherlands": "네덜란드",
    "New Zealand": "뉴질랜드",
    "Norway": "노르웨이",
    "Panama": "파나마",
    "Paraguay": "파라과이",
    "Portugal": "포르투갈",
    "Qatar": "카타르",
    "Saudi Arabia": "사우디아라비아",
    "Scotland": "스코틀랜드",
    "Senegal": "세네갈",
    "South Africa": "남아공",
    "Spain": "스페인",
    "Sweden": "스웨덴",
    "Switzerland": "스위스",
    "Tunisia": "튀니지",
    "Türkiye": "튀르키예",
    "Turkey": "튀르키예",
    "USA": "미국",
    "United States": "미국",
    "Uruguay": "우루과이",
    "Uzbekistan": "우즈베키스탄",
}


def to_korean(name: str, code: str | None = None) -> str:
    """영문명/코드를 한글명으로. 매핑 없으면 원본 영문명 유지."""
    if code and code in KO_BY_CODE:
        return KO_BY_CODE[code]
    if name in KO_BY_NAME:
        return KO_BY_NAME[name]
    return name
